import {
  IconAccel,
  IconBoard,
  IconCalculator,
  IconCameraMap,
  IconEnergy,
  IconMedia,
  IconMusic,
  IconPages,
  IconReplay,
  IconSpeed,
  IconWorld,
} from "../icons.js";
import { defineAppManifest } from "./manifest.js";
import type { VatioAppManifest } from "./types";

const fixedToolCapabilities = {
  draggable: true,
  resizable: false,
  minimizable: true,
  closable: true,
  restorable: true,
  maximizable: false,
  snap: false,
  preserveIntrinsicWidth: true,
} as const;

const snappingWindowCapabilities = {
  draggable: true,
  resizable: true,
  minimizable: true,
  closable: true,
  restorable: true,
  fullscreen: true,
  maximizable: true,
  snap: true,
} as const;

export const BUILTIN_APP_MANIFESTS = [
  defineAppManifest({
    id: "vatio.speed",
    title: "Vatio Speed",
    shortTitle: "Speed",
    description: "Live GPS speedometer, trip recording, speed alerts, and camera-aware driving tools.",
    kind: "core-app",
    version: "1.0.0",
    icon: IconSpeed,
    i18nKey: "speedometer",
    route: "/",
    aliases: ["/speed"],
    entry: () => import("../apps/speed/index.js"),
    surfaces: ["main-route", "start-menu", "launcher"],
    order: 10,
    permissions: [
      "gps.read",
      "gps.highAccuracy",
      "storage.app",
      "audio.playback",
      "audio.background",
      "alerts.speed",
      "driveRecording.read",
      "driveRecording.write",
      "cloud.sync",
      "i18n.read",
      "settings.read",
      "settings.write",
      "shell.window",
      "shell.launchApp",
    ],
    services: ["gps", "audio", "driveRecording", "drivingAlerts", "cloudSync", "shell", "storage", "i18n", "settings"],
    tags: ["driving", "gps", "local-first"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "stable",
    metadata: {
      legacyToolId: "route:speed",
      legacyHref: "#/speed",
    },
  }),
  defineAppManifest({
    id: "vatio.board",
    title: "Vatio Board",
    shortTitle: "Board",
    description: "Touch-first drawing board with local drafts and optional VatioLibre sync.",
    kind: "core-app",
    version: "1.0.0",
    icon: IconBoard,
    i18nKey: "openBoard",
    route: "/board",
    entry: () => import("../app/views/BoardView.js"),
    surfaces: ["main-route", "start-menu", "launcher"],
    order: 20,
    permissions: [
      "storage.app",
      "storage.media",
      "cloud.sync",
      "auth.session",
      "network.backend",
      "i18n.read",
      "settings.read",
      "settings.write",
      "shell.window",
      "shell.launchApp",
    ],
    services: ["auth", "cloudSync", "shell", "storage", "i18n", "settings"],
    tags: ["drawing", "offline", "cloud-sync"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "stable",
    metadata: {
      legacyToolId: "route:board",
    },
  }),
  defineAppManifest({
    id: "vatio.replay",
    title: "Drive Replay",
    shortTitle: "Replay",
    description: "Replay local and synced GPS drive sessions with charts and map playback.",
    kind: "core-app",
    version: "1.0.0",
    icon: IconReplay,
    i18nKey: "driveReplay",
    route: "/replay",
    entry: () => import("../app/views/ReplayView.js"),
    surfaces: ["main-route", "start-menu", "launcher"],
    order: 30,
    permissions: [
      "storage.app",
      "driveRecording.read",
      "cloud.sync",
      "auth.session",
      "network.backend",
      "i18n.read",
      "shell.launchApp",
    ],
    services: ["driveRecording", "auth", "cloudSync", "shell", "storage", "i18n"],
    tags: ["driving", "replay", "history"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "stable",
    metadata: {
      legacyToolId: "route:replay",
    },
  }),
  defineAppManifest({
    id: "vatio.accel",
    title: "Vatio Accel",
    shortTitle: "Accel",
    description: "GPS acceleration timer and local run history for Tesla and mobile.",
    kind: "core-app",
    version: "1.0.0",
    icon: IconAccel,
    i18nKey: "accelerationTest",
    route: "/accel",
    entry: () => import("../app/views/AccelView.js"),
    surfaces: ["main-route", "start-menu", "launcher"],
    order: 40,
    permissions: [
      "gps.read",
      "gps.highAccuracy",
      "storage.app",
      "cloud.sync",
      "auth.session",
      "network.backend",
      "i18n.read",
      "settings.read",
      "settings.write",
      "shell.launchApp",
    ],
    services: ["gps", "auth", "cloudSync", "shell", "storage", "i18n", "settings"],
    tags: ["driving", "gps", "performance"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "stable",
    metadata: {
      legacyToolId: "route:accel",
    },
  }),
  defineAppManifest({
    id: "vatio.library",
    title: "Cloud Library",
    shortTitle: "Library",
    description: "Browse VatioLibre cloud records and media while preserving local-first behavior.",
    kind: "core-app",
    version: "1.0.0",
    icon: IconWorld,
    i18nKey: "cloudLibrary",
    route: "/library",
    entry: () => import("../app/views/LibraryView.js"),
    surfaces: ["main-route", "start-menu", "launcher"],
    order: 50,
    permissions: [
      "storage.app",
      "storage.media",
      "cloud.sync",
      "auth.session",
      "network.backend",
      "i18n.read",
      "settings.read",
      "shell.launchApp",
    ],
    services: ["auth", "cloudSync", "shell", "storage", "i18n", "settings"],
    tags: ["library", "cloud", "media"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "beta",
    metadata: {
      legacyToolId: "route:library",
    },
  }),
  defineAppManifest({
    id: "vatio.appManager",
    title: "App Manager",
    shortTitle: "Apps",
    description: "Internal VatioBoard OS app inventory and diagnostics.",
    kind: "system-app",
    version: "1.0.0",
    icon: IconPages,
    i18nKey: "appManager",
    route: "/apps",
    entry: () => import("../app/views/AppsView.js"),
    surfaces: ["main-route", "start-menu", "launcher", "app-manager"],
    order: 55,
    permissions: [
      "storage.app",
      "i18n.read",
      "settings.read",
      "shell.window",
      "shell.launchApp",
    ],
    services: ["shell", "storage", "i18n", "settings"],
    tags: ["system", "diagnostics"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "internal",
    metadata: {
      legacyToolId: "route:apps",
    },
  }),
  defineAppManifest({
    id: "vatio.calculator",
    title: "Calculator",
    shortTitle: "Calc",
    description: "Floating calculator for quick arithmetic inside VatioBoard.",
    kind: "tool-app",
    version: "1.0.0",
    icon: IconCalculator,
    i18nKey: "calculator",
    entry: () => import("../apps/calculator/index.js"),
    surfaces: ["shell-window", "start-menu", "taskbar", "launcher"],
    order: 60,
    permissions: ["storage.app", "i18n.read", "settings.read", "settings.write", "shell.window"],
    services: ["shell", "storage", "i18n", "settings"],
    window: {
      shellWindowId: "calculator",
      mode: "floating",
      defaultBounds: { left: 24, top: 88, width: 320 },
      capabilities: {
        ...fixedToolCapabilities,
        maxWidth: 320,
      },
      restoreOnBoot: true,
      lazy: false,
    },
    tags: ["tool", "math"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "stable",
    metadata: {
      legacyToolId: "calculator",
      legacyToolSurfaces: ["floating-tools"],
      legacyShellKind: "tool",
    },
  }),
  defineAppManifest({
    id: "vatio.energy",
    title: "Energy",
    shortTitle: "Energy",
    description: "Trip cost and EV energy calculator.",
    kind: "tool-app",
    version: "1.0.0",
    icon: IconEnergy,
    i18nKey: "energy",
    entry: () => import("../apps/energy/index.js"),
    surfaces: ["shell-window", "start-menu", "taskbar", "launcher"],
    order: 70,
    permissions: ["storage.app", "i18n.read", "shell.window", "settings.read", "settings.write"],
    services: ["shell", "storage", "i18n", "settings"],
    window: {
      shellWindowId: "energy",
      mode: "floating",
      defaultBounds: { left: 32, top: 112, width: 640 },
      capabilities: {
        ...fixedToolCapabilities,
        maxWidth: 640,
      },
      restoreOnBoot: true,
      lazy: false,
    },
    tags: ["tool", "ev"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "stable",
    metadata: {
      legacyToolId: "energy",
      legacyToolSurfaces: ["floating-tools"],
      legacyShellKind: "tool",
    },
  }),
  defineAppManifest({
    id: "vatio.cameraMap",
    title: "Camera Map",
    shortTitle: "Camera Map",
    description: "Floating camera map with GPS-follow and local camera data.",
    kind: "tool-app",
    version: "1.0.0",
    icon: IconCameraMap,
    i18nKey: "cameraMapTitle",
    entry: () => import("../apps/camera-map/index.js"),
    surfaces: ["shell-window", "start-menu", "taskbar", "launcher"],
    order: 80,
    permissions: [
      "gps.read",
      "gps.highAccuracy",
      "storage.app",
      "network.backend",
      "i18n.read",
      "shell.window",
      "settings.read",
      "settings.write",
    ],
    services: ["gps", "shell", "storage", "i18n", "settings"],
    window: {
      shellWindowId: "camera-map",
      mode: "floating",
      defaultBounds: { left: 40, top: 96, width: 560, height: 420 },
      capabilities: {
        ...snappingWindowCapabilities,
        snapZones: ["left", "right", "top", "bottom", "center", "top-left", "top-right", "bottom-left", "bottom-right"],
      },
      restoreOnBoot: true,
      lazy: true,
    },
    tags: ["tool", "gps", "map"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "beta",
    metadata: {
      legacyToolId: "camera-map",
      legacyToolSurfaces: ["floating-tools"],
      legacyShellKind: "tool",
    },
  }),
  defineAppManifest({
    id: "vatio.speedAlerts",
    title: "Speed Alerts",
    shortTitle: "Alerts",
    description: "Floating speed and camera alert control panel.",
    kind: "tool-app",
    version: "1.0.0",
    icon: IconSpeed,
    i18nKey: "speedAlertsTitle",
    entry: () => import("../apps/speed-alerts/index.js"),
    surfaces: ["shell-window", "start-menu", "taskbar", "launcher"],
    order: 90,
    permissions: [
      "gps.read",
      "gps.highAccuracy",
      "audio.playback",
      "audio.background",
      "alerts.speed",
      "storage.app",
      "i18n.read",
      "shell.window",
      "shell.launchApp",
      "settings.read",
      "settings.write",
    ],
    services: ["gps", "audio", "drivingAlerts", "shell", "storage", "i18n", "settings"],
    window: {
      shellWindowId: "speed-alerts",
      mode: "floating",
      defaultBounds: { left: 48, top: 120, width: 380, height: 360 },
      capabilities: {
        draggable: true,
        resizable: true,
        minimizable: true,
        closable: true,
        restorable: true,
      },
      restoreOnBoot: true,
      lazy: false,
    },
    tags: ["tool", "driving", "alerts"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "stable",
    metadata: {
      legacyToolId: "speed-alerts",
      legacyToolSurfaces: ["floating-tools"],
      legacyShellKind: "tool",
    },
  }),
  defineAppManifest({
    id: "vatio.player",
    title: "Player",
    shortTitle: "Player",
    description: "Persistent audio player shell window.",
    kind: "media-app",
    version: "1.0.0",
    icon: IconMusic,
    i18nKey: "audioPlayer",
    entry: () => import("../apps/player/index.js"),
    surfaces: ["shell-window", "taskbar", "launcher"],
    order: 100,
    permissions: [
      "audio.playback",
      "audio.background",
      "storage.app",
      "storage.media",
      "network.backend",
      "auth.session",
      "i18n.read",
      "shell.window",
      "settings.read",
      "settings.write",
    ],
    services: ["audio", "auth", "shell", "storage", "i18n", "settings"],
    window: {
      shellWindowId: "player",
      mode: "floating",
      defaultBounds: { left: 56, top: 96, width: 340 },
      capabilities: {
        ...fixedToolCapabilities,
        fullscreen: false,
        maxWidth: 340,
      },
      restoreOnBoot: true,
      lazy: false,
    },
    tags: ["media", "audio"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "beta",
    metadata: {
      legacyToolId: "player",
      legacyShellKind: "media",
    },
  }),
  defineAppManifest({
    id: "vatio.milkdrop",
    title: "Milkdrop",
    shortTitle: "Milkdrop",
    description: "Audio visualizer shell window.",
    kind: "visualizer-app",
    version: "1.0.0",
    icon: IconMedia,
    i18nKey: "milkdropTitle",
    entry: () => import("../apps/milkdrop/index.js"),
    surfaces: ["shell-window", "taskbar", "launcher"],
    order: 110,
    permissions: [
      "audio.playback",
      "storage.app",
      "i18n.read",
      "shell.window",
      "settings.read",
      "settings.write",
    ],
    services: ["audio", "shell", "storage", "i18n", "settings"],
    window: {
      shellWindowId: "milkdrop",
      mode: "floating",
      defaultBounds: { left: 64, top: 104, width: 640, height: 420 },
      capabilities: snappingWindowCapabilities,
      restoreOnBoot: true,
      lazy: false,
    },
    tags: ["media", "visualizer"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "experimental",
    metadata: {
      legacyToolId: "milkdrop",
      legacyShellKind: "visualizer",
    },
  }),
] satisfies readonly VatioAppManifest[];
