import {
  IconAccel,
  IconCameraMap,
  IconEnergy,
  IconMedia,
  IconMusic,
  IconPages,
  IconReplay,
  IconSpeed,
  IconWorld,
} from "../icons.js";
import { boardAppManifest } from "../apps/board/manifest.js";
import { calculatorAppManifest } from "../apps/calculator/manifest.js";
import { codeRainAppManifest } from "../apps/code-rain/manifest.js";
import { ttsAppManifest } from "../apps/tts/manifest.js";
import { premiumClockAppManifest } from "../apps/premium-clock/manifest.js";
import { speedAppManifest } from "../apps/speed/manifest.js";
import { defineAppManifest } from "./manifest.js";
import type { VatioAppManifest } from "./types";

const fixedToolCapabilities = {
  draggable: true,
  resizable: false,
  minimizable: true,
  closable: true,
  restorable: true,
  maximizable: false,
  snap: false,
  preserveIntrinsicWidth: true,
} as const;

const snappingWindowCapabilities = {
  draggable: true,
  resizable: true,
  minimizable: true,
  closable: true,
  restorable: true,
  fullscreen: true,
  maximizable: true,
  snap: true,
} as const;

export const BUILTIN_APP_MANIFESTS = [
  speedAppManifest,
  boardAppManifest,
  // TODO: migrate the remaining centralized built-in manifests into app-owned
  // manifest.ts files as each app is touched.
  defineAppManifest({
    id: "vatio.replay",
    title: "Drive Replay",
    shortTitle: "Replay",
    description: "Replay local and synced GPS drive sessions with charts and map playback.",
    kind: "core-app",
    version: "1.0.0",
    icon: IconReplay,
    theme: {
      color: "#7c3aed",
      color2: "#a78bfa",
    },
    i18nKey: "driveReplay",
    route: "/replay",
    entry: () => import("../apps/replay/index.js"),
    surfaces: ["main-route", "start-menu", "launcher"],
    order: 30,
    permissions: [
      "storage.app",
      "driveRecording.read",
      "cloud.sync",
      "auth.session",
      "network.backend",
      "i18n.read",
      "settings.read",
      "settings.write",
      "shell.launchApp",
    ],
    services: ["driveRecording", "auth", "cloudSync", "shell", "storage", "i18n", "settings"],
    tags: ["driving", "replay", "history"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "stable",
    metadata: {
      legacyToolId: "route:replay",
    },
  }),
  defineAppManifest({
    id: "vatio.accel",
    title: "Vatio Accel",
    shortTitle: "Accel",
    description: "GPS acceleration timer and local run history for Tesla and mobile.",
    kind: "core-app",
    version: "1.0.0",
    icon: IconAccel,
    theme: {
      color: "#14b8a6",
      color2: "#5eead4",
    },
    i18nKey: "accelerationTest",
    route: "/accel",
    entry: () => import("../apps/accel/index.js"),
    surfaces: ["main-route", "start-menu", "launcher"],
    order: 40,
    permissions: [
      "gps.read",
      "gps.highAccuracy",
      "storage.app",
      "cloud.sync",
      "auth.session",
      "network.backend",
      "i18n.read",
      "settings.read",
      "settings.write",
      "shell.launchApp",
    ],
    services: ["gps", "auth", "cloudSync", "shell", "storage", "i18n", "settings"],
    tags: ["driving", "gps", "performance"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "stable",
    metadata: {
      legacyToolId: "route:accel",
    },
  }),
  defineAppManifest({
    id: "vatio.library",
    title: "Cloud Library",
    shortTitle: "Library",
    description: "Browse VatioLibre cloud records and media while preserving local-first behavior.",
    kind: "core-app",
    version: "1.0.0",
    icon: IconWorld,
    theme: {
      color: "#0f766e",
      color2: "#5eead4",
    },
    i18nKey: "cloudLibrary",
    route: "/library",
    entry: () => import("../apps/library/index.js"),
    surfaces: ["main-route", "start-menu", "launcher"],
    order: 50,
    permissions: [
      "storage.app",
      "storage.media",
      "cloud.sync",
      "auth.session",
      "network.backend",
      "i18n.read",
      "settings.read",
      "settings.write",
      "shell.launchApp",
    ],
    services: ["auth", "cloudSync", "shell", "storage", "i18n", "settings"],
    tags: ["library", "cloud", "media"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "beta",
    metadata: {
      legacyToolId: "route:library",
    },
  }),
  defineAppManifest({
    id: "vatio.appManager",
    title: "App Manager",
    shortTitle: "Apps",
    description: "Internal VatioBoard OS app inventory and diagnostics.",
    kind: "system-app",
    version: "1.0.0",
    icon: IconPages,
    theme: {
      color: "#16a34a",
      color2: "#86efac",
    },
    i18nKey: "appManager",
    route: "/apps",
    entry: () => import("../app/views/AppsView.js"),
    surfaces: ["main-route", "start-menu", "launcher", "app-manager"],
    order: 55,
    permissions: [
      "storage.app",
      "i18n.read",
      "settings.read",
      "shell.window",
      "shell.launchApp",
    ],
    services: ["shell", "storage", "i18n", "settings"],
    tags: ["system", "diagnostics"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "internal",
    metadata: {
      legacyToolId: "route:apps",
    },
  }),
  codeRainAppManifest,
  calculatorAppManifest,
  premiumClockAppManifest,
  ttsAppManifest,
  defineAppManifest({
    id: "vatio.energy",
    title: "Energy",
    shortTitle: "Energy",
    description: "Trip cost and EV energy calculator.",
    kind: "tool-app",
    version: "1.0.0",
    icon: IconEnergy,
    theme: {
      color: "#f59e0b",
      color2: "#facc15",
    },
    i18nKey: "energy",
    entry: () => import("../apps/energy/index.js"),
    surfaces: ["shell-window", "start-menu", "taskbar", "launcher"],
    order: 70,
    permissions: ["storage.app", "i18n.read", "shell.window", "settings.read", "settings.write"],
    services: ["shell", "storage", "i18n", "settings"],
    window: {
      shellWindowId: "energy",
      mode: "floating",
      defaultBounds: { left: 32, top: 112, width: 640 },
      capabilities: {
        ...fixedToolCapabilities,
        minWidth: 320,
        minHeight: 570,
        maxWidth: 640,
      },
      restoreOnBoot: true,
      lazy: false,
    },
    tags: ["tool", "ev"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "stable",
    metadata: {
      legacyToolId: "energy",
      legacyToolSurfaces: ["floating-tools"],
      legacyShellKind: "tool",
    },
  }),
  defineAppManifest({
    id: "vatio.cameraMap",
    title: "Camera Map",
    shortTitle: "Camera Map",
    description: "Floating camera map with GPS-follow and local camera data.",
    kind: "tool-app",
    version: "1.0.0",
    icon: IconCameraMap,
    theme: {
      color: "#2563eb",
      color2: "#60a5fa",
    },
    i18nKey: "cameraMapTitle",
    entry: () => import("../apps/camera-map/index.js"),
    surfaces: ["shell-window", "start-menu", "taskbar", "launcher"],
    order: 80,
    permissions: [
      "gps.read",
      "gps.highAccuracy",
      "storage.app",
      "network.backend",
      "i18n.read",
      "shell.window",
      "settings.read",
      "settings.write",
    ],
    services: ["gps", "shell", "storage", "i18n", "settings"],
    window: {
      shellWindowId: "camera-map",
      mode: "floating",
      defaultBounds: { left: 40, top: 96, width: 560, height: 460 },
      capabilities: {
        ...snappingWindowCapabilities,
        minWidth: 420,
        minHeight: 460,
        snapZones: ["left", "right", "top", "bottom", "center", "top-left", "top-right", "bottom-left", "bottom-right"],
      },
      restoreOnBoot: true,
      lazy: true,
    },
    tags: ["tool", "gps", "map"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "beta",
    metadata: {
      legacyToolId: "camera-map",
      legacyToolSurfaces: ["floating-tools"],
      legacyShellKind: "tool",
    },
  }),
  defineAppManifest({
    id: "vatio.speedAlerts",
    title: "Speed Alerts",
    shortTitle: "Alerts",
    description: "Floating speed and camera alert control panel.",
    kind: "tool-app",
    version: "1.0.0",
    icon: IconSpeed,
    theme: {
      color: "#7c3aed",
      color2: "#a78bfa",
    },
    i18nKey: "speedAlertsTitle",
    entry: () => import("../apps/speed-alerts/index.js"),
    surfaces: ["shell-window", "start-menu", "taskbar", "launcher"],
    order: 90,
    permissions: [
      "gps.read",
      "gps.highAccuracy",
      "audio.playback",
      "audio.background",
      "alerts.speed",
      "storage.app",
      "i18n.read",
      "shell.window",
      "shell.launchApp",
      "settings.read",
      "settings.write",
    ],
    services: ["gps", "audio", "drivingAlerts", "shell", "storage", "i18n", "settings"],
    window: {
      shellWindowId: "speed-alerts",
      mode: "floating",
      defaultBounds: { left: 48, top: 120, width: 430, height: 620 },
      capabilities: {
        draggable: true,
        resizable: true,
        minimizable: true,
        closable: true,
        restorable: true,
        minWidth: 320,
        minHeight: 420,
      },
      restoreOnBoot: true,
      lazy: false,
    },
    tags: ["tool", "driving", "alerts"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "stable",
    metadata: {
      legacyToolId: "speed-alerts",
      legacyToolSurfaces: ["floating-tools"],
      legacyShellKind: "tool",
    },
  }),
  defineAppManifest({
    id: "vatio.player",
    title: "Player",
    shortTitle: "Player",
    description: "Persistent audio player shell window.",
    kind: "media-app",
    version: "1.0.0",
    icon: IconMusic,
    theme: {
      color: "#db2777",
      color2: "#f472b6",
    },
    i18nKey: "audioPlayer",
    entry: () => import("../apps/player/index.js"),
    surfaces: ["shell-window", "taskbar", "launcher"],
    order: 100,
    permissions: [
      "audio.playback",
      "audio.background",
      "storage.app",
      "storage.media",
      "network.backend",
      "auth.session",
      "i18n.read",
      "shell.window",
      "settings.read",
      "settings.write",
    ],
    services: ["audio", "auth", "shell", "storage", "i18n", "settings"],
    window: {
      shellWindowId: "player",
      mode: "floating",
      defaultBounds: { left: 56, top: 96, width: 340 },
      capabilities: {
        ...fixedToolCapabilities,
        fullscreen: false,
        minWidth: 320,
        minHeight: 220,
        maxWidth: 340,
      },
      restoreOnBoot: true,
      lazy: false,
    },
    tags: ["media", "audio"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "beta",
    metadata: {
      legacyToolId: "player",
      legacyShellKind: "media",
    },
  }),
  defineAppManifest({
    id: "vatio.milkdrop",
    title: "Milkdrop",
    shortTitle: "Milkdrop",
    description: "Audio visualizer shell window.",
    kind: "visualizer-app",
    version: "1.0.0",
    icon: IconMedia,
    theme: {
      color: "#16a34a",
      color2: "#4ade80",
    },
    i18nKey: "milkdropTitle",
    entry: () => import("../apps/milkdrop/index.js"),
    surfaces: ["shell-window", "taskbar", "launcher"],
    order: 110,
    permissions: [
      "audio.playback",
      "storage.app",
      "i18n.read",
      "shell.window",
      "settings.read",
      "settings.write",
    ],
    services: ["audio", "shell", "storage", "i18n", "settings"],
    window: {
      shellWindowId: "milkdrop",
      mode: "floating",
      defaultBounds: { left: 64, top: 104, width: 640, height: 420 },
      capabilities: {
        ...snappingWindowCapabilities,
        minWidth: 320,
        minHeight: 260,
      },
      restoreOnBoot: true,
      lazy: false,
    },
    tags: ["media", "visualizer"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "experimental",
    metadata: {
      legacyToolId: "milkdrop",
      legacyShellKind: "visualizer",
    },
  }),
  defineAppManifest({
    id: "vatio.offlineReadiness",
    title: "Offline Readiness",
    shortTitle: "Offline",
    description: "Internal background diagnostics for local-first storage and offline shell readiness.",
    kind: "background-service",
    version: "1.0.0",
    icon: IconPages,
    theme: {
      color: "#64748b",
      color2: "#94a3b8",
    },
    i18nKey: "offlineReady",
    surfaces: ["background", "app-manager"],
    order: 120,
    permissions: ["storage.app", "i18n.read", "settings.read"],
    services: ["storage", "i18n", "settings"],
    lifecycle: {
      autostart: true,
      keepAlive: false,
      restoreOnBoot: false,
    },
    tags: ["system", "offline", "diagnostics"],
    localFirst: true,
    teslaOptimized: true,
    offlineCapable: true,
    status: "internal",
    metadata: {
      protected: true,
    },
  }),
] satisfies readonly VatioAppManifest[];
